language: generic
sudo: required # docker needs supersuser permissions
services:
  - docker # travis CI will automatically install docker

before_install: # series of steps that have to happen before we start our tests
  # tagging convention "docker_username/git_repo_name"
  # we use Dockerfile.dev because for testing we need to install additional dependencies that are not needed in PROD env
  - docker build -t truebot/docker-react -f Dockerfile.dev .

script: # commands needed for running tests, if return status =! 0 Travis will assume there was error
  - docker run -e CI=true truebot/docker-react npm run test
deploy: # commands to deploy to AWS
  provider: elasticbeanstalk # that informs what AWS service we will use
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"

  # bucket_name is s3 server name
  # how to find: search for s3, open, search for provider & region
  bucket_name: "elasticbeanstalk-us-east-2-161456857908"
  bucket_path: "docker-react"
  on: # deploy only the mentioned branch in this case "master"
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
